### ISSUE TITLE
missing sentence/para in src chapter

### ISSUE THREAD

**Issue by mdsumner** [hadley/r-pkgs#420] opened 2017-07-29 21:34 UTC
There's a dangling unfinished sentence here: 

https://github.com/hadley/r-pkgs/blob/master/src.rmd#development-workflow-src-workflow

```
If you have C objects that persist between reloads, and you change the data 
structure, then it's
```

I'd quite like to now how it ends!

**Comment by jennybc** [comment] 2018-02-10 19:56
Duplicate of #456 which has more detail at this point.

**Closed by jennybc** 2018-02-10 19:56 UTC
