### ISSUE TITLE
Java source code folder should be specified in .Rbuildignore instead of .Rinstignore

### ISSUE THREAD

**Issue by wlamnz** [hadley/r-pkgs#736] opened 2021-09-30 20:55 UTC
In Chapter 16.2 [Other Languages](https://r-pkgs.org/inst.html#inst-other-langs), it is implied that the /java folder containing the source code should go in the root level of the R package, but contradicts itself by saying it should be ignored in the .Rinstignore, which should be .Rbuildignore.

> Java is a special case because you need to include both the source code (which should go in java/ and be listed in .Rinstignore), and the compiled jar files (which should go in inst/java). Make sure to add rJava to Imports.

**Comment by hadley** [comment] 2022-03-09 21:47
Effectively a duplicate of #223; we're going to get out of the business of giving advice about java in this book.

**Closed by hadley** 2022-03-09 21:47 UTC
Labels: Installed files
