### ISSUE TITLE
Mention build time dependencies

### ISSUE THREAD

**Issue by dpprdan** [hadley/r-pkgs#611] opened 2019-11-27 13:48 UTC
Triggered by Hadley's [tweet](https://twitter.com/hadleywickham/status/1199493296986288128) I was wondering whether mentioning the issue of build time dependencies (or rather how to avoid them) might be a good idea here or whether that is too specific?

I, for one, was not really aware of the problem before I saw https://github.com/r-lib/memoise/issues/76 and Gabor's [post(s) to r-devel](https://stat.ethz.ch/pipermail/r-devel/2017-January/073647.html) linked therein.

**Comment by jennybc** [comment] 2019-11-27 16:08
This is basically a duplicate of (or included in) #550.

**Closed by jennybc** 2019-11-27 16:08 UTC
