### ISSUE TITLE
As a scientist, I want to make my software more FAIR.

### ISSUE THREAD

**Issue by rbirkelbach** [hadley/r-pkgs#494] opened 2018-07-12 12:55 UTC
In spirit of the FAIR principles, I want to make R software more FAIR. Hence, I think it would be good to document how to add the ORCiD to the authors part of the DESCRIPTION file.

**Comment by hadley** [comment] 2019-01-29 21:10
What are the FAIR principles?

**Comment by rbirkelbach** [comment] 2019-01-31 11:11
It's an acronym for "Findable Accessible Interoperable Reusable". This issue is about the finable part. As many researchers frequently change their emails because universities do not let them keep their email, it would be great to include a persistent identifier (hence the ORCiD) so that there's no problem when trying to contact them. This is important especially when the author has a very common name. I think it initially started as principles for research data, but it starts being picked up in the research software community as well. Here are some slides discussing some aspects of it: https://indico.cern.ch/event/588219/contributions/2384979/attachments/1426152/2189855/FAIR_Software_Principles_CERN_March_2017.pdf

I have created a pr a while ago: https://github.com/hadley/r-pkgs/pull/495

**Comment by hadley** [comment] 2019-02-06 12:51
Duplicate of #460

**Closed by hadley** 2019-02-06 12:51 UTC
