### ISSUE TITLE
Ch 10.1 - final bullet point incomplete

### ISSUE THREAD

**Issue by MWilson92** [hadley/r-pkgs#883] opened 2022-11-16 09:36 UTC
The final bullet point of ch 10.1 Introduction seems to be incomplete. At the minute reads as:

> - The dependencies of your package, which

This appears to be a typo with missing content afterwards.

**Comment by jennybc** [comment] 2022-11-16 16:59
Duplicate of #880 :grimacing:

**Closed by jennybc** 2022-11-16 16:59 UTC
