### ISSUE TITLE
Ch. 2.6 - output does not match description in text.

### ISSUE THREAD

**Issue by KirkDSL** [hadley/r-pkgs#723] opened 2021-07-21 17:06 UTC
Chapter 2.6 starts with the following text:

It is not too hard to find a puzzling operation involving factors. Let’s see what happens when we catenate two factors.

```
(a <- factor(c("character", "hits", "your", "eyeballs")))
#> [1] character hits      your      eyeballs 
#> Levels: character eyeballs hits your
(b <- factor(c("but", "integer", "where it", "counts")))
#> [1] but      integer  where it counts  
#> Levels: but counts integer where it
c(a, b)
#> [1] character hits      your      eyeballs  but       integer  
#> [7] where it  counts   
#> 8 Levels: character eyeballs hits your but counts ... where it
```

The output doesn't actually make sense in that the concatenation of factors seems to produce the expected output.  On my machine, I see this:

```
> (a <- factor(c("character", "hits", "your", "eyeballs")))
[1] character hits      your      eyeballs 
Levels: character eyeballs hits your
> (b <- factor(c("but", "integer", "where it", "counts")))
[1] but      integer  where it counts  
Levels: but counts integer where it
> c(a, b)
[1] 1 3 4 2 1 3 4 2
```

Which is consistent with what the text describes.  Somehow during the book build, the correct output is generated which makes the discussion a bit confusing.

**Comment by jennybc** [comment] 2021-11-06 19:15
Duplicate of #709

**Closed by jennybc** 2021-11-06 19:15 UTC
