### ISSUE TITLE
Ch 2.6 First Function Example doesn't make sense anymore

### ISSUE THREAD

**Issue by mjkanji** [hadley/r-pkgs#722] opened 2021-07-20 17:34 UTC
The example under Chapter 2.6, which is used as the reason for creating our own function, no longer works as expected. I'm referring to this section specifically:

```
(a <- factor(c("character", "hits", "your", "eyeballs")))
#> [1] character hits      your      eyeballs 
#> Levels: character eyeballs hits your
(b <- factor(c("but", "integer", "where it", "counts")))
#> [1] but      integer  where it counts  
#> Levels: but counts integer where it
c(a, b)
#> [1] character hits      your      eyeballs  but       integer  
#> [7] where it  counts   
#> 8 Levels: character eyeballs hits your but counts ... where it
```

> Huh? **_Many people do not expect the result of catenating two factors to be an integer vector consisting of the numbers 1, 2, 3, and 4._**

As can be seen from the snippet inside the book itself, there's a disconnect between the text and how R now works when concatenating factors. An integer vector is no longer returned and, therefore, the `fbind` function used as an example in this section becomes quite redundant.

**Comment by jennybc** [comment] 2021-07-21 01:38
Duplicate of #709

**Closed by jennybc** 2021-07-21 01:38 UTC
